// Generates the dotted land mask used by the hero globe (assets/js/land-dots.js).
// Points are spread evenly over the sphere (Fibonacci lattice) and kept when they fall on land
// according to Natural Earth 1:50m data from the world-atlas package.
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoContains } from "d3-geo";

const root = new URL("..", import.meta.url).pathname;
const topo = JSON.parse(readFileSync(root + "node_modules/world-atlas/land-50m.json", "utf8"));
const land = feature(topo, topo.objects.land);

const N = 18000;
const golden = Math.PI * (3 - Math.sqrt(5));
const out = [];
for (let i = 0; i < N; i++) {
  const y = 1 - (i / (N - 1)) * 2;
  const lat = (Math.asin(y) * 180) / Math.PI;
  let lon = (((i * golden) * 180) / Math.PI) % 360;
  if (lon > 180) lon -= 360;
  if (lat < -60) continue; // skip Antarctica, it only adds noise at the bottom of the globe
  if (geoContains(land, [lon, lat])) out.push(Math.round(lat * 100), Math.round(lon * 100));
}
const bytes = Buffer.from(new Int16Array(out).buffer).toString("base64");
writeFileSync(root + "assets/js/land-dots.js",
  `// Generated by tools/build-globe.mjs. ${out.length / 2} land points, Int16 pairs of lat*100, lon*100.\nexport default "${bytes}";\n`);
console.log("land dots:", out.length / 2, "bytes:", bytes.length);

// Country markers for the globe, derived from data/orgs.json so the counts never drift.
const { countries } = JSON.parse(readFileSync(root + "data/orgs.json", "utf8"));
const mapped = countries.filter((c) => c.lat !== null).map((c) => [c.code, c.name, c.lat, c.lon, c.count]);
writeFileSync(root + "assets/js/globe-data.js",
  `// Generated by tools/build-globe.mjs from data/orgs.json. [code, name, lat, lon, organizations]\n` +
  `export const ORIGIN = [31.22, 75.77]; // Punjab, India: where the reports are sent from\n` +
  `export const COUNTRIES = ${JSON.stringify(mapped)};\n`);
console.log("globe countries:", mapped.length);
